spring.application.name=ms-pedidos
server.port=8082

# Conexión MySQL con soporte para variables de entorno
spring.datasource.url=jdbc:mysql://localhost:3306/smartlogix?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

ms.inventario.base-url=http://localhost:8081

# Para usar este perfil, ejecutar: java -jar app.jar --spring.profiles.active=dev
# O configurar variable de entorno: SPRING_PROFILES_ACTIVE=dev
